---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files: 
    - vars/common.yml
    - vars/vault
  tasks:
    - import_tasks: tasks/create_windows_vm.yml
      tags: 
        - windows
    - import_tasks: tasks/create_linux_vm.yml
      tags: 
        - linux
      when: false

- hosts: windows
  tasks:
    - import_tasks: tasks/deploy_website.yml
      tags: 
        - deploy
