- name: Create Windows VM
  azure_rm_virtualmachine:
    resource_group: "{{ my_group }}"
    name: "{{ windows.vm_name }}"
    vm_size: "{{ windows.vm_size }}"
    admin_username: "{{ my_user }}"
    admin_password: "{{ my_password }}"
    os_type: Windows
    image:
      offer: "{{ windows.image.offer }}"
      publisher: "{{ windows.image.publisher }}"
      sku: "{{ windows.image.sku }}"
      version: "{{ windows.image.version }}"
